@ApiGateway_HostAddress = http://localhost:5090

#if (EnableOpenAPI)
GET {{ApiGateway_HostAddress}}/openapi/v1.json
Accept: application/json

###
#endif

GET {{ApiGateway_HostAddress}}/weatherforecast/
Accept: application/json

###
